version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./Website:/var/www/html/public"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./etc/nginx/logs:/var/log/nginx"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "Nginx"
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./Website:/var/www/html/public"
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "PHP"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "PHPMyAdmin"
    mysqldb:
        image: mariadb:${MARIADB_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mariadb/innodb-fix.cnf:/etc/mysql/conf.d/innodb-fix.cnf"
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "MySQL"
