version: '3'
services:

    web:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./Website:/var/www/html/public:ro"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./etc/logs/nginx:/var/log/nginx"
            - "./etc/logs/letsencrypt:/var/log/letsencrypt"
            - "./etc/letsencrypt/certs:/etc/letsencrypt"
            - "./etc/letsencrypt/data:/data/letsencrypt"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=localhost
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "Nginx"

    php:
        image: nanoninja/php-fpm:7.2
        container_name: php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./Website:/var/www/html/public"
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "PHP"

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysqldb
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "PHPMyAdmin"

    mysqldb:
        image: mariadb:10.3.8
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mariadb/innodb-fix.cnf:/etc/mysql/conf.d/innodb-fix.cnf"
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "MySQL"

    tomcat:
        image: tomcat:9.0.10-jre10-slim
        container_name: tomcat
        ports:
            - "8082:8082"
            - "8443:8443"
        restart: always
        volumes:
            - "./Website:/usr/local/tomcat/webapps/ROOT"
            - "./etc/tomcat:/usr/local/tomcat/conf"
        depends_on:
            - mysqldb
#        logging:
#            driver: splunk
#            options:
#                splunk-token: "e1c56fa1-9f7c-4d2c-ba8f-989b15d85008"
#                splunk-url: "https://127.0.0.1:8088"
#                splunk-insecureskipverify: "true"
#                tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
#                labels: "Tomcat"
